string header
uint16 protocol_version
uint8 packet_number
uint8 players_per_team
string game_type
string state
uint8 first_half
uint8 kick_off_team
string secondary_state

uint8 team_p
string submode

uint8 drop_in_team
uint16 drop_in_time
uint16 secs_remaining
uint16 secondary_time

#atributos del equipo en general
uint8 team_n
uint8 team_c
uint8 score 
uint8 p_shoot
uint8 coach_s




#atributos de cada robot 
string penalty_1 
uint8 time_p_1
uint8 warnings_1
uint8 ycards_1
uint8 rcards_1
uint8 gkeeper_1

